-- aggregate_frames.sql
-- Per-month frame counts (binary presence, COUNTIF), GenAI/governance
-- filters identical to extract_genai_gov.sql. See MERGE_PLAN.md.
-- GENERATED by src/build_query.py — do not hand-edit. Run `python -m src.build_query --write` to refresh.

SELECT
  FORMAT_DATE(
    '%Y-%m',
    PARSE_DATE('%Y%m%d', SUBSTR(CAST(DATE AS STRING), 1, 8))
  ) AS month,

  COUNT(*) AS total_articles,

  -- Frame: innovation_opportunity
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'innovation|innovative|breakthrough|opportunity|promise|benefit|potential|growth|boost|productivity|efficiency|transform|progress|competitiveness|powerful|smarter|human level|milestone|cutting edge|state of the art|most capable|outperforms|aces|beats humans|superhuman|reasoning|launches|launch|unveils|unveiled|releases|released|rolls out|introduces|introducing|debuts|new model|new feature|new tool|announces|announced|rollout|upgrade|automate|workflow|save time|streamline|augment|assistant|help you|coding|scientific|discovery|study finds|medical|diagnosis|drug discovery|healthcare|cancer|scientists')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'innovation|innovative|breakthrough|opportunity|promise|benefit|potential|growth|boost|productivity|efficiency|transform|progress|competitiveness|powerful|smarter|human level|milestone|cutting edge|state of the art|most capable|outperforms|aces|beats humans|superhuman|reasoning|launches|launch|unveils|unveiled|releases|released|rolls out|introduces|introducing|debuts|new model|new feature|new tool|announces|announced|rollout|upgrade|automate|workflow|save time|streamline|augment|assistant|help you|coding|scientific|discovery|study finds|medical|diagnosis|drug discovery|healthcare|cancer|scientists')
  ) AS frame_innovation_opportunity,

  -- Frame: risk_safety
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'risk|risks|harm|harms|danger|threat|safety|unsafe|misuse|abuse|catastrophic|existential|crisis|ai safety|extinction|out of control|rogue|doomsday|warns|warning|fears|scary|alarming|alarm|cyber|cybersecurity|hack|hacking|hackers|malware|phishing|exploit|breach|weapon|weapons|drone|drones|national security|attack|scam|scams|hallucination|hallucinate|hallucinations|inaccurate|fabricated|unreliable|flawed|made up|makes up|lies|false|wrong|accuracy|errors|mistakes|confidently wrong|teen|teens|children|kids|child|mental health|suicide|self harm|vulnerable|addiction|students')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'risk|risks|harm|harms|danger|threat|safety|unsafe|misuse|abuse|catastrophic|existential|crisis|ai safety|extinction|out of control|rogue|doomsday|warns|warning|fears|scary|alarming|alarm|cyber|cybersecurity|hack|hacking|hackers|malware|phishing|exploit|breach|weapon|weapons|drone|drones|national security|attack|scam|scams|hallucination|hallucinate|hallucinations|inaccurate|fabricated|unreliable|flawed|made up|makes up|lies|false|wrong|accuracy|errors|mistakes|confidently wrong|teen|teens|children|kids|child|mental health|suicide|self harm|vulnerable|addiction|students')
  ) AS frame_risk_safety,

  -- Frame: regulation_governance
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'regulation|regulatory|regulator|law|legislation|policy|rules|oversight|compliance|enforcement|framework|standard|audit|governance|regulate|regulating|ai act|guidelines|code of practice|laws|ban|banned|bans|restrict|restricted|restrictions|prohibit|moratorium|pause|blocks|blocked|blocking|regulators|ftc|congress|senate|white house|watchdog|probe|investigation|investigating|antitrust|lawmakers|brussels|government|lawsuit|lawsuits|sued|sues|suing|court|legal|settlement|settle|liability|trial|judge|litigation')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'regulation|regulatory|regulator|law|legislation|policy|rules|oversight|compliance|enforcement|framework|standard|audit|governance|regulate|regulating|ai act|guidelines|code of practice|laws|ban|banned|bans|restrict|restricted|restrictions|prohibit|moratorium|pause|blocks|blocked|blocking|regulators|ftc|congress|senate|white house|watchdog|probe|investigation|investigating|antitrust|lawmakers|brussels|government|lawsuit|lawsuits|sued|sues|suing|court|legal|settlement|settle|liability|trial|judge|litigation')
  ) AS frame_regulation_governance,

  -- Frame: rights_privacy
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'privacy|data protection|personal data|human rights|fundamental rights|civil liberties|surveillance|bias|fairness|transparency|consent|gdpr|data collection|data breach|scraping|scraped|your data|user data|copyright|intellectual property|plagiarism|infringement|authors|artists|training data|stolen|pirated|copyrighted|creators|spying|facial recognition|tracking|monitor|monitoring|spy|biased|discrimination|racist|racism|sexist|discriminate|stereotypes|prejudice')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'privacy|data protection|personal data|human rights|fundamental rights|civil liberties|surveillance|bias|fairness|transparency|consent|gdpr|data collection|data breach|scraping|scraped|your data|user data|copyright|intellectual property|plagiarism|infringement|authors|artists|training data|stolen|pirated|copyrighted|creators|spying|facial recognition|tracking|monitor|monitoring|spy|biased|discrimination|racist|racism|sexist|discriminate|stereotypes|prejudice')
  ) AS frame_rights_privacy,

  -- Frame: economic_competition_labour
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'jobs|workers|automation|labour market|labor market|workforce|competition|market power|monopoly|race|competitiveness|investment|job|layoffs|unemployment|replace|replacing|replaced|labor|hiring|career|employees|white collar|invest|funding|valuation|billion|trillion|stocks|revenue|profit|ipo|startup|raises|raised|deal|funding round|market value|china|chinese|arms race|ai race|sovereignty|dominance|us china|beijing|race for|rival|rivals|compete|competing|competitor|competitors|takes on|versus|battle|race to|challenger|outpace|showdown|catch up')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'jobs|workers|automation|labour market|labor market|workforce|competition|market power|monopoly|race|competitiveness|investment|job|layoffs|unemployment|replace|replacing|replaced|labor|hiring|career|employees|white collar|invest|funding|valuation|billion|trillion|stocks|revenue|profit|ipo|startup|raises|raised|deal|funding round|market value|china|chinese|arms race|ai race|sovereignty|dominance|us china|beijing|race for|rival|rivals|compete|competing|competitor|competitors|takes on|versus|battle|race to|challenger|outpace|showdown|catch up')
  ) AS frame_economic_competition_labour,

  -- Frame: misinformation_integrity
  COUNTIF(
    REGEXP_CONTAINS(LOWER(Quotations), r'misinformation|disinformation|deepfake|fake news|synthetic media|manipulation|propaganda|scam|impersonation|information integrity|deepfakes|cloned voice|face swap|fake video|fake image|fake photos|false information|fabricated content|fake content|manipulate|election|elections|fraud|impersonate|voters|authenticity|credibility|watermark|detect ai|ai detector')
    OR REGEXP_CONTAINS(LOWER(AllNames), r'misinformation|disinformation|deepfake|fake news|synthetic media|manipulation|propaganda|scam|impersonation|information integrity|deepfakes|cloned voice|face swap|fake video|fake image|fake photos|false information|fabricated content|fake content|manipulate|election|elections|fraud|impersonate|voters|authenticity|credibility|watermark|detect ai|ai detector')
  ) AS frame_misinformation_integrity

FROM `gdelt-bq.gdeltv2.gkg_partitioned`
WHERE DATE(_PARTITIONTIME) >= '2022-11-01'
  AND DATE(_PARTITIONTIME) <= '2026-06-30'

  -- GenAI filter (identical predicate to extract_genai_gov.sql)
  AND (
    REGEXP_CONTAINS(LOWER(AllNames),
      r'chatgpt|generative ai|genai|gen ai|large language model|llm|foundation model|frontier model|gpt-4|gpt4|gpt-5|gpt5|claude|anthropic|gemini|bard|dall-e|dalle|stable diffusion|midjourney|text-to-image|image generator|copilot|grok|llama')
    OR
    REGEXP_CONTAINS(LOWER(Quotations),
      r'chatgpt|generative ai|large language model|foundation model|frontier model|anthropic')
)

  -- Governance filter (identical predicate to extract_genai_gov.sql)
  AND (
    REGEXP_CONTAINS(LOWER(Quotations),
      r'governance|regulation|regulatory|regulator|policy|oversight|law|legislation|ai act|eu ai act|framework|guidelines|compliance|enforcement|accountability|liability|responsible ai|trustworthy ai|ethical ai|risk management|guardrails|safeguards|ai safety|human rights|privacy|data protection|misinformation|deepfake')
    OR
    REGEXP_CONTAINS(V2Themes,
      r'ECON_REGULATION|UNGP|HUMAN_RIGHTS|EPU_CATS_REGULATION|EPU_POLICY_LAW|EPU_POLICY_REGULATION|LEGISLATION|WB_831_GOVERNANCE|WB_2089_ETHICS_AND_CODES_OF_CONDUCT|WB_845_LEGAL_AND_REGULATORY_FRAMEWORK|WB_851_INTELLECTUAL_PROPERTY_RIGHTS|WB_838_PUBLIC_ACCOUNTABILITY_MECHANISMS|WB_279_ICT_STRATEGY_POLICY_AND_REGULATION|WB_282_ICT_POLICY_REGULATORY_FRAMEWORK')
    OR
    REGEXP_CONTAINS(LOWER(DocumentIdentifier),
      r'-regulat|-policy-|-legislat|-governance-|-safety-|-security-|-threat|-warns-|-warning-|-ethic|-privacy-|-rights-|-oversight-|-copyright|-lawsuit|-banned-|-ban-|-ai-act')
)

GROUP BY month
ORDER BY month;
