-- extract_genai_gov.sql
-- Main corpus extraction: generative-AI governance articles, Nov 2022 – Jun 2026.
--
-- Strategy:
--   GenAI signal  → LOWER(AllNames) or LOWER(Quotations) matches at least one
--                   term from GENAI_LEXICON (proper nouns and model names appear
--                   in AllNames; contextual mentions appear in Quotations).
--   Governance signal → LOWER(Quotations) or V2Themes matches at least one term
--                       from GOV_LEXICON.
--
-- The LIKE clause blocks below are generated by src/build_query.py.
-- Re-run that script after editing dictionaries.py to refresh this file.
--
-- Estimated scan: ~3–8 TB depending on date range; use _PARTITIONTIME filters
-- to limit cost. Consider splitting by year for large exports.

SELECT
  DATE,
  SourceCommonName,
  DocumentIdentifier,
  V2Themes,
  V2Tone,
  V2Locations,
  AllNames,
  Quotations
FROM `gdelt-bq.gdeltv2.gkg_partitioned`
WHERE DATE(_PARTITIONTIME) >= '2022-11-01'
  AND DATE(_PARTITIONTIME) <= '2026-06-30'

  -- GenAI filter: at least one term from GENAI_LEXICON
  AND (
    LOWER(AllNames) LIKE '%chatgpt%'
    OR LOWER(AllNames) LIKE '%generative ai%'
    OR LOWER(AllNames) LIKE '%genai%'
    OR LOWER(AllNames) LIKE '%gen ai%'
    OR LOWER(AllNames) LIKE '%large language model%'
    OR LOWER(AllNames) LIKE '%llm%'
    OR LOWER(AllNames) LIKE '%foundation model%'
    OR LOWER(AllNames) LIKE '%frontier model%'
    OR LOWER(AllNames) LIKE '%gpt-4%'
    OR LOWER(AllNames) LIKE '%gpt4%'
    OR LOWER(AllNames) LIKE '%gpt-5%'
    OR LOWER(AllNames) LIKE '%gpt5%'
    OR LOWER(AllNames) LIKE '%claude%'
    OR LOWER(AllNames) LIKE '%gemini%'
    OR LOWER(AllNames) LIKE '%bard%'
    OR LOWER(AllNames) LIKE '%dall-e%'
    OR LOWER(AllNames) LIKE '%dalle%'
    OR LOWER(AllNames) LIKE '%stable diffusion%'
    OR LOWER(AllNames) LIKE '%midjourney%'
    OR LOWER(AllNames) LIKE '%text-to-image%'
    OR LOWER(AllNames) LIKE '%image generator%'
    OR LOWER(Quotations) LIKE '%chatgpt%'
    OR LOWER(Quotations) LIKE '%generative ai%'
    OR LOWER(Quotations) LIKE '%large language model%'
    OR LOWER(Quotations) LIKE '%foundation model%'
    OR LOWER(Quotations) LIKE '%frontier model%'
  )

  -- Governance filter: at least one term from GOV_LEXICON
  AND (
    LOWER(Quotations) LIKE '%governance%'
    OR LOWER(Quotations) LIKE '%regulation%'
    OR LOWER(Quotations) LIKE '%regulatory%'
    OR LOWER(Quotations) LIKE '%regulator%'
    OR LOWER(Quotations) LIKE '%policy%'
    OR LOWER(Quotations) LIKE '%oversight%'
    OR LOWER(Quotations) LIKE '%legislation%'
    OR LOWER(Quotations) LIKE '%ai act%'
    OR LOWER(Quotations) LIKE '%eu ai act%'
    OR LOWER(Quotations) LIKE '%compliance%'
    OR LOWER(Quotations) LIKE '%enforcement%'
    OR LOWER(Quotations) LIKE '%accountability%'
    OR LOWER(Quotations) LIKE '%liability%'
    OR LOWER(Quotations) LIKE '%responsible ai%'
    OR LOWER(Quotations) LIKE '%trustworthy ai%'
    OR LOWER(Quotations) LIKE '%ethical ai%'
    OR LOWER(Quotations) LIKE '%risk management%'
    OR LOWER(Quotations) LIKE '%guardrails%'
    OR LOWER(Quotations) LIKE '%safeguards%'
    OR LOWER(Quotations) LIKE '%ai safety%'
    OR LOWER(Quotations) LIKE '%human rights%'
    OR LOWER(Quotations) LIKE '%privacy%'
    OR LOWER(Quotations) LIKE '%data protection%'
    OR LOWER(Quotations) LIKE '%misinformation%'
    OR LOWER(Quotations) LIKE '%deepfake%'
    OR V2Themes LIKE '%ECON_REGULATION%'
    OR V2Themes LIKE '%UNGP%'
    OR V2Themes LIKE '%HUMAN_RIGHTS%'
  );
