-- extract_genai_gov.sql
-- Main corpus extraction: generative-AI governance articles.
-- Strategy: GenAI signal (AllNames/Quotations) AND governance signal
-- (Quotations keyword OR V2Themes theme tag OR DocumentIdentifier
-- url slug). See MERGE_PLAN.md for the full rationale.
-- GENERATED by src/build_query.py — do not hand-edit. Run `python -m src.build_query --write` to refresh.

SELECT
  DATE,
  SourceCommonName,
  DocumentIdentifier,
  V2Themes,
  V2Tone,
  V2Locations,
  AllNames,
  Quotations
FROM `gdelt-bq.gdeltv2.gkg_partitioned`
WHERE DATE(_PARTITIONTIME) >= '2022-11-01'
  AND DATE(_PARTITIONTIME) <= '2026-06-30'

  -- GenAI filter: at least one term from GENAI_LEXICON
  AND (
    LOWER(AllNames) LIKE '%chatgpt%'
    OR LOWER(AllNames) LIKE '%generative ai%'
    OR LOWER(AllNames) LIKE '%genai%'
    OR LOWER(AllNames) LIKE '%gen ai%'
    OR LOWER(AllNames) LIKE '%large language model%'
    OR LOWER(AllNames) LIKE '%llm%'
    OR LOWER(AllNames) LIKE '%foundation model%'
    OR LOWER(AllNames) LIKE '%frontier model%'
    OR LOWER(AllNames) LIKE '%gpt-4%'
    OR LOWER(AllNames) LIKE '%gpt4%'
    OR LOWER(AllNames) LIKE '%gpt-5%'
    OR LOWER(AllNames) LIKE '%gpt5%'
    OR LOWER(AllNames) LIKE '%claude%'
    OR LOWER(AllNames) LIKE '%anthropic%'
    OR LOWER(AllNames) LIKE '%gemini%'
    OR LOWER(AllNames) LIKE '%bard%'
    OR LOWER(AllNames) LIKE '%dall-e%'
    OR LOWER(AllNames) LIKE '%dalle%'
    OR LOWER(AllNames) LIKE '%stable diffusion%'
    OR LOWER(AllNames) LIKE '%midjourney%'
    OR LOWER(AllNames) LIKE '%text-to-image%'
    OR LOWER(AllNames) LIKE '%image generator%'
    OR LOWER(AllNames) LIKE '%copilot%'
    OR LOWER(AllNames) LIKE '%grok%'
    OR LOWER(AllNames) LIKE '%llama%'
    OR
    LOWER(Quotations) LIKE '%chatgpt%'
    OR LOWER(Quotations) LIKE '%generative ai%'
    OR LOWER(Quotations) LIKE '%large language model%'
    OR LOWER(Quotations) LIKE '%foundation model%'
    OR LOWER(Quotations) LIKE '%frontier model%'
    OR LOWER(Quotations) LIKE '%anthropic%'
)

  -- Governance filter: GOV_LEXICON keyword in Quotations, OR a
  -- GOV_THEME_TAGS code in V2Themes, OR a GOV_URL_SLUGS substring
  -- in the article URL.
  AND (
    LOWER(Quotations) LIKE '%governance%'
    OR LOWER(Quotations) LIKE '%regulation%'
    OR LOWER(Quotations) LIKE '%regulatory%'
    OR LOWER(Quotations) LIKE '%regulator%'
    OR LOWER(Quotations) LIKE '%policy%'
    OR LOWER(Quotations) LIKE '%oversight%'
    OR LOWER(Quotations) LIKE '%law%'
    OR LOWER(Quotations) LIKE '%legislation%'
    OR LOWER(Quotations) LIKE '%ai act%'
    OR LOWER(Quotations) LIKE '%eu ai act%'
    OR LOWER(Quotations) LIKE '%framework%'
    OR LOWER(Quotations) LIKE '%guidelines%'
    OR LOWER(Quotations) LIKE '%compliance%'
    OR LOWER(Quotations) LIKE '%enforcement%'
    OR LOWER(Quotations) LIKE '%accountability%'
    OR LOWER(Quotations) LIKE '%liability%'
    OR LOWER(Quotations) LIKE '%responsible ai%'
    OR LOWER(Quotations) LIKE '%trustworthy ai%'
    OR LOWER(Quotations) LIKE '%ethical ai%'
    OR LOWER(Quotations) LIKE '%risk management%'
    OR LOWER(Quotations) LIKE '%guardrails%'
    OR LOWER(Quotations) LIKE '%safeguards%'
    OR LOWER(Quotations) LIKE '%ai safety%'
    OR LOWER(Quotations) LIKE '%human rights%'
    OR LOWER(Quotations) LIKE '%privacy%'
    OR LOWER(Quotations) LIKE '%data protection%'
    OR LOWER(Quotations) LIKE '%misinformation%'
    OR LOWER(Quotations) LIKE '%deepfake%'
    OR
    V2Themes LIKE '%ECON_REGULATION%'
    OR V2Themes LIKE '%UNGP%'
    OR V2Themes LIKE '%HUMAN_RIGHTS%'
    OR V2Themes LIKE '%EPU_CATS_REGULATION%'
    OR V2Themes LIKE '%EPU_POLICY_LAW%'
    OR V2Themes LIKE '%EPU_POLICY_REGULATION%'
    OR V2Themes LIKE '%LEGISLATION%'
    OR V2Themes LIKE '%WB_831_GOVERNANCE%'
    OR V2Themes LIKE '%WB_2089_ETHICS_AND_CODES_OF_CONDUCT%'
    OR V2Themes LIKE '%WB_845_LEGAL_AND_REGULATORY_FRAMEWORK%'
    OR V2Themes LIKE '%WB_851_INTELLECTUAL_PROPERTY_RIGHTS%'
    OR V2Themes LIKE '%WB_838_PUBLIC_ACCOUNTABILITY_MECHANISMS%'
    OR V2Themes LIKE '%WB_279_ICT_STRATEGY_POLICY_AND_REGULATION%'
    OR V2Themes LIKE '%WB_282_ICT_POLICY_REGULATORY_FRAMEWORK%'
    OR
    LOWER(DocumentIdentifier) LIKE '%-regulat%'
    OR LOWER(DocumentIdentifier) LIKE '%-policy-%'
    OR LOWER(DocumentIdentifier) LIKE '%-legislat%'
    OR LOWER(DocumentIdentifier) LIKE '%-governance-%'
    OR LOWER(DocumentIdentifier) LIKE '%-safety-%'
    OR LOWER(DocumentIdentifier) LIKE '%-security-%'
    OR LOWER(DocumentIdentifier) LIKE '%-threat%'
    OR LOWER(DocumentIdentifier) LIKE '%-warns-%'
    OR LOWER(DocumentIdentifier) LIKE '%-warning-%'
    OR LOWER(DocumentIdentifier) LIKE '%-ethic%'
    OR LOWER(DocumentIdentifier) LIKE '%-privacy-%'
    OR LOWER(DocumentIdentifier) LIKE '%-rights-%'
    OR LOWER(DocumentIdentifier) LIKE '%-oversight-%'
    OR LOWER(DocumentIdentifier) LIKE '%-copyright%'
    OR LOWER(DocumentIdentifier) LIKE '%-lawsuit%'
    OR LOWER(DocumentIdentifier) LIKE '%-banned-%'
    OR LOWER(DocumentIdentifier) LIKE '%-ban-%'
    OR LOWER(DocumentIdentifier) LIKE '%-ai-act%'
);
