"""
Generate the two BigQuery queries (extract_genai_gov, count_genai_total)
entirely from the lexicons in data/lexicons/*.yaml via src/dictionaries.py.

queries/*.sql are build artifacts — regenerate with
`python -m src.build_query --write` after editing any YAML lexicon file.

Usage:
    python -m src.build_query            # print GenAI/governance filter fragments
    python -m src.build_query --write    # regenerate queries/*.sql on disk
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pandas as pd

from src.dictionaries import (
    FRAME_DICTS,
    GENAI_LEXICON,
    GENAI_LEXICON_CONTEXTUAL,
    GOV_LEXICON,
    GOV_THEME_TAGS,
    GOV_URL_SLUGS,
    MILESTONES,
    STUDY_END_DATE,
    STUDY_START_DATE,
)

TABLE = "`gdelt-bq.gdeltv2.gkg_partitioned`"

EXTRACT_COLUMNS = [
    "DATE",
    "SourceCommonName",
    "DocumentIdentifier",
    "V2Themes",
    "V2Tone",
    "V2Locations",
    "AllNames",
    "Quotations",
]

# Fields to search for each lexicon (order matters: cheaper fields first).
# V2Themes is deliberately excluded from _GOV_FIELDS: it holds structured
# theme codes (e.g. TAX_FNCACT), not prose, so English keywords like "act" or
# "law" would match it on accidental substrings rather than real signal.
# Theme-code matching against V2Themes is handled separately via
# GOV_THEME_TAGS/_GOV_THEME_FIELD with exact code substrings.
_GOV_FIELDS = ["Quotations"]
_GOV_URL_FIELD = ["DocumentIdentifier"]
_GOV_THEME_FIELD = ["V2Themes"]

_GENERATED_HEADER = "-- GENERATED by src/build_query.py — do not hand-edit. Run `python -m src.build_query --write` to refresh.\n"


# ---------------------------------------------------------------------------
# Term -> pattern helpers
# ---------------------------------------------------------------------------

# Only true RE2 metacharacters need escaping; spaces and hyphens are literal
# in RE2 outside character classes and are embedded raw (matching the
# project's existing, dry-run-verified convention) rather than via Python's
# re.escape, which over-escapes spaces/hyphens with backslash sequences that
# aren't validated against BigQuery's regex engine.
_RE2_SPECIAL = re.compile(r"([.^$*+?()\[\]{}|\\])")


def _regexp_escape(term: str) -> str:
    return _RE2_SPECIAL.sub(r"\\\1", term)


def build_regexp_pattern(terms: list[str]) -> str:
    """Alternation pattern for REGEXP_CONTAINS, e.g. 'a|b|c'.

    Same escaping/joining convention as src/preprocessing.py's
    assign_frame_flags, so SQL-side and Python-side frame matching can never
    silently diverge in how dictionary terms become patterns.
    """
    return "|".join(_regexp_escape(t) for t in terms)


def _flatten_lexicon(lexicon: list[str] | dict[str, list[str]]) -> list[str]:
    """Accept either a flat list or a language-keyed dict and return a flat list."""
    if isinstance(lexicon, dict):
        return [term for terms in lexicon.values() for term in terms]
    return list(lexicon)


def build_like_block(terms: list[str], fields: list[str], indent: int = 4, lower: bool = True) -> str:
    """Build a SQL OR block: each term x each field as a LIKE clause.

    GDELT theme codes (V2Themes) are always upper-case by convention, so pass
    lower=False for those to match the existing style in extract_genai_gov.sql
    rather than wrapping both sides in LOWER() for no reason.
    """
    pad = " " * indent
    clauses = []
    for field in fields:
        for term in terms:
            escaped = term.replace("'", "\\'")
            target = f"LOWER({field})" if lower else field
            clauses.append(f"{target} LIKE '%{escaped}%'")
    first, *rest = clauses
    lines = [pad + first] + [pad + "OR " + c for c in rest]
    return "\n".join(lines)


def _regexp_clause(field: str, terms: list[str], lower: bool = True, indent: int = 4) -> str:
    pad = " " * indent
    target = f"LOWER({field})" if lower else field
    pattern = build_regexp_pattern(terms)
    return f"{pad}REGEXP_CONTAINS({target},\n{pad}  r'{pattern}')"


# ---------------------------------------------------------------------------
# GenAI / governance filter blocks
# ---------------------------------------------------------------------------

def build_genai_filter(style: str = "like", indent: int = 4) -> str:
    """Full parenthesized GenAI filter: AllNames (full lexicon) OR Quotations (contextual subset)."""
    pad = " " * indent
    if style == "like":
        all_names = build_like_block(GENAI_LEXICON, ["AllNames"], indent=indent)
        quotations = build_like_block(_flatten_lexicon(GENAI_LEXICON_CONTEXTUAL), ["Quotations"], indent=indent)
    elif style == "regexp":
        all_names = _regexp_clause("AllNames", GENAI_LEXICON, indent=indent)
        quotations = _regexp_clause("Quotations", _flatten_lexicon(GENAI_LEXICON_CONTEXTUAL), indent=indent)
    else:
        raise ValueError(f"unknown style: {style}")
    return f"(\n{all_names}\n{pad}OR\n{quotations}\n)"


def build_gov_filter(style: str = "like", indent: int = 4) -> str:
    """Full parenthesized governance filter: keyword-in-Quotations OR theme-tag-in-V2Themes OR url-slug-in-DocumentIdentifier."""
    pad = " " * indent
    if style == "like":
        keyword = build_like_block(_flatten_lexicon(GOV_LEXICON), _GOV_FIELDS, indent=indent)
        theme = build_like_block(GOV_THEME_TAGS, _GOV_THEME_FIELD, indent=indent, lower=False)
        url = build_like_block(GOV_URL_SLUGS, _GOV_URL_FIELD, indent=indent)
    elif style == "regexp":
        keyword = _regexp_clause("Quotations", _flatten_lexicon(GOV_LEXICON), indent=indent)
        theme = _regexp_clause("V2Themes", GOV_THEME_TAGS, lower=False, indent=indent)
        url = _regexp_clause("DocumentIdentifier", GOV_URL_SLUGS, indent=indent)
    else:
        raise ValueError(f"unknown style: {style}")
    return f"(\n{keyword}\n{pad}OR\n{theme}\n{pad}OR\n{url}\n)"


# ---------------------------------------------------------------------------
# Full queries
# ---------------------------------------------------------------------------

def build_extract_query(start: str = STUDY_START_DATE, end: str = STUDY_END_DATE) -> str:
    """Main corpus extraction query, equivalent to extract_genai_gov.sql."""
    columns = ",\n  ".join(EXTRACT_COLUMNS)
    genai = build_genai_filter("like")
    gov = build_gov_filter("like")
    return (
        f"SELECT\n  {columns}\n"
        f"FROM {TABLE}\n"
        f"WHERE DATE(_PARTITIONTIME) >= '{start}'\n"
        f"  AND DATE(_PARTITIONTIME) <= '{end}'\n\n"
        f"  -- GenAI filter: at least one term from GENAI_LEXICON\n"
        f"  AND {genai}\n\n"
        f"  -- Governance filter: GOV_LEXICON keyword in Quotations, OR a\n"
        f"  -- GOV_THEME_TAGS code in V2Themes, OR a GOV_URL_SLUGS substring\n"
        f"  -- in the article URL.\n"
        f"  AND {gov};\n"
    )


def build_count_total_query(start: str = STUDY_START_DATE, end: str = STUDY_END_DATE) -> str:
    """Monthly GenAI article counts WITHOUT governance filter, equivalent to count_genai_total.sql.

    Divide extract_genai_gov.sql monthly counts by these to compute the
    governance coverage rate used in the methods validation figure.
    """
    genai = build_genai_filter("like")
    return (
        "SELECT\n"
        "  FORMAT_DATE(\n"
        "    '%Y-%m',\n"
        "    PARSE_DATE('%Y%m%d', SUBSTR(CAST(DATE AS STRING), 1, 8))\n"
        "  ) AS month,\n\n"
        "  COUNT(*) AS total_articles\n\n"
        f"FROM {TABLE}\n"
        f"WHERE DATE(_PARTITIONTIME) >= '{start}'\n"
        f"  AND DATE(_PARTITIONTIME) <= '{end}'\n\n"
        "  -- GenAI filter only — no governance filter.\n"
        f"  AND {genai}\n\n"
        "GROUP BY month\n"
        "ORDER BY month;\n"
    )


def milestone_windows(milestones: list[dict] | None = None, window: int = 3) -> list[tuple[str, str, str]]:
    """Compute each milestone's [start, end] window as (name, start_date, end_date) strings.

    Uses pandas.Period month arithmetic so off-by-one bugs (e.g. the previous
    hand-computed event_windows.sql under-covering bletchley_summit by one
    month) can't recur.
    """
    milestones = milestones or MILESTONES
    out = []
    for m in milestones:
        pivot = pd.Period(m["date"][:7], freq="M")
        start = (pivot - window).start_time.date().isoformat()
        end = (pivot + window).end_time.date().isoformat()
        out.append((m["name"], start, end))
    return out


# ---------------------------------------------------------------------------
# Write to disk
# ---------------------------------------------------------------------------

def write_all_queries(out_dir: str | Path = "queries") -> None:
    """Regenerate queries/*.sql from the current dictionaries.py contents."""
    out_dir = Path(out_dir)
    files = {
        "extract_genai_gov.sql": (
            "-- extract_genai_gov.sql\n"
            "-- Main corpus extraction: generative-AI governance articles.\n"
            "-- GenAI signal (AllNames/Quotations) AND governance signal\n"
            "-- (Quotations keyword OR V2Themes theme tag OR DocumentIdentifier url slug).\n"
            + _GENERATED_HEADER
            + "\n"
            + build_extract_query()
        ),
        "count_genai_total.sql": (
            "-- count_genai_total.sql\n"
            "-- Monthly GenAI article counts WITHOUT governance filter.\n"
            "-- Divide extract_genai_gov monthly counts by these to get the\n"
            "-- governance coverage rate (used in the methods validation figure).\n"
            + _GENERATED_HEADER
            + "\n"
            + build_count_total_query()
        ),
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (out_dir / name).write_text(content)


def main() -> None:
    if "--write" in sys.argv[1:]:
        write_all_queries()
        print("Wrote queries/extract_genai_gov.sql, count_genai_total.sql")
        return

    print("-- GenAI filter block")
    print(build_genai_filter("like"))
    print()
    print("-- Governance filter block: keyword-in-text + theme tags + URL slugs")
    print(build_gov_filter("like"))


if __name__ == "__main__":
    main()
